name = "time-fantasy-characters"

[sheets._tf_template]
file = "sheets/$tf_template.png"
cell_w = 26
cell_h = 36

[sheets.animals1]
file = "sheets/animals1.png"
cell_w = 26
cell_h = 36

[sheets.animation1]
file = "sheets/animation1.png"
cell_w = 47
cell_h = 50

[sheets.animation2]
file = "sheets/animation2.png"
cell_w = 47
cell_h = 50

[sheets.bonus1]
file = "sheets/bonus1.png"
cell_w = 26
cell_h = 36

[sheets.chara2]
file = "sheets/chara2.png"
cell_w = 26
cell_h = 36

[sheets.chara3]
file = "sheets/chara3.png"
cell_w = 26
cell_h = 36

[sheets.chara4]
file = "sheets/chara4.png"
cell_w = 26
cell_h = 36

[sheets.chara5]
file = "sheets/chara5.png"
cell_w = 26
cell_h = 36

[sheets.chests]
file = "sheets/chests.png"
cell_w = 42
cell_h = 36

[sheets.emote2]
file = "sheets/emote2.png"
cell_w = 26
cell_h = 36

[sheets.emote3]
file = "sheets/emote3.png"
cell_w = 26
cell_h = 36

[sheets.emote4]
file = "sheets/emote4.png"
cell_w = 26
cell_h = 36

[sheets.emote5]
file = "sheets/emote5.png"
cell_w = 26
cell_h = 36

[sheets.military1]
file = "sheets/military1.png"
cell_w = 26
cell_h = 36

[sheets.military2]
file = "sheets/military2.png"
cell_w = 26
cell_h = 36

[sheets.military3]
file = "sheets/military3.png"
cell_w = 26
cell_h = 36

[sheets.npc1]
file = "sheets/npc1.png"
cell_w = 26
cell_h = 36

[sheets.npc2]
file = "sheets/npc2.png"
cell_w = 26
cell_h = 36

[sheets.npc3]
file = "sheets/npc3.png"
cell_w = 26
cell_h = 36

[sheets.npc4]
file = "sheets/npc4.png"
cell_w = 26
cell_h = 36
