name = "time-fantasy-tiles"

[sheets.castle]
file = "TILESETS/castle.png"
cell_w = 16
cell_h = 16

[sheets.doors]
file = "TILESETS/animated/doors.png"
cell_w = 16
cell_h = 32

[sheets.world]
file = "TILESETS/world.png"
cell_w = 16
cell_h = 16
