name = "time-fantasy-icons1"

[sheets.icons_full_16]
file = "fullcolor/icons_full_16.png"
cell_w = 16
cell_h = 16

[sheets.icons_full_16_2]
file = "updated_layout/icons_full_16.png"
cell_w = 16
cell_h = 16

[sheets.icons_full_24]
file = "fullcolor/icons_full_24.png"
cell_w = 24
cell_h = 24

[sheets.icons_full_32]
file = "fullcolor/icons_full_32.png"
cell_w = 32
cell_h = 32

[sheets.icons_full_32_2]
file = "updated_layout/icons_full_32.png"
cell_w = 32
cell_h = 32

[sheets.icons_tf_16]
file = "updated_layout/icons_tf_16.png"
cell_w = 16
cell_h = 16

[sheets.icons_tf_32]
file = "updated_layout/icons_tf_32.png"
cell_w = 32
cell_h = 32

[sheets.tficons_limited_16]
file = "tfcolor/tficons_limited_16.png"
cell_w = 16
cell_h = 16

[sheets.tficons_limited_24]
file = "tfcolor/tficons_limited_24.png"
cell_w = 24
cell_h = 24

[sheets.tficons_limited_32]
file = "tfcolor/tficons_limited_32.png"
cell_w = 32
cell_h = 32
